---
name: cmakebuild

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:

  binaries_windows_x64:
    name: Binaries for Windows x64
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x64]

        include:
          # Prettier run names.
          - {os: windows-2019, name: VS 2019}

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags
          git submodule init
          git submodule update

      - name: Configure and Build
        run: |
          $VER_FILE_SHORT=Get-Content .\VERSION
          New-Item -ItemType "directory" -Path ${{ matrix.arch }} -Force
          cd ${{ matrix.arch }}
          'set(CMAKE_CXX_FLAGS_RELEASE "/MT")' | out-file .\toolChain.cmake -append
          'set(CMAKE_C_FLAGS_RELEASE "/MT")' | out-file .\toolChain.cmake -append
          cmake.exe -G "Visual Studio 16 2019" -A ${{ matrix.arch }} -S .. `
                                              -DCMAKE_TOOLCHAIN_FILE=./toolChain.cmake `
                                              -DN2N_OPTION_USE_PORTMAPPING=ON -B .
          MSBuild.exe ALL_BUILD.vcxproj /t:Build /p:Configuration=Release

          $RELEASE_DIR = "Release" + $VER_FILE_SHORT
          mv Release  $RELEASE_DIR

      - name: Create binary dir
        run: |
          mkdir -p windows_${{ matrix.arch }}
          cp -r ${{ matrix.arch }}/Release* windows_${{ matrix.arch }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows_${{ matrix.arch }}
          path: windows_${{ matrix.arch }}


  binaries_windows_x86:
    name: Binaries for Windows x86
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x86]

        include:
          # Prettier run names.
          - {os: windows-2019, name: VS 2019}

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags
          git submodule init
          git submodule update

      - name: Configure and Build
        run: |
          $VER_FILE_SHORT=Get-Content .\VERSION
          New-Item -ItemType "directory" -Path ${{ matrix.arch }} -Force
          cd ${{ matrix.arch }}
          'set(CMAKE_CXX_FLAGS_RELEASE "/MT")' | out-file .\toolChain.cmake -append
          'set(CMAKE_C_FLAGS_RELEASE "/MT")' | out-file .\toolChain.cmake -append
          cmake.exe -G "Visual Studio 16 2019" -A Win32 -S .. `
                                              -DCMAKE_TOOLCHAIN_FILE=./toolChain.cmake `
                                              -DN2N_OPTION_USE_PORTMAPPING=ON -B .
          MSBuild.exe ALL_BUILD.vcxproj /t:Build /p:Configuration=Release

          $RELEASE_DIR = "Release" + $VER_FILE_SHORT
          mv Release  $RELEASE_DIR

      - name: Create binary dir
        run: |
          mkdir -p windows_${{ matrix.arch }}
          cp -r ${{ matrix.arch }}/Release* windows_${{ matrix.arch }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows_${{ matrix.arch }}
          path: windows_${{ matrix.arch }}

  binaries_linux_x64:
    name: Binaries for linux
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        arch: 
          - amd64

    steps:
      - uses: actions/checkout@v2

      - name: Fix Checkout
        run: |
          git fetch --force --tags
          git sumodule init
          git sumodule update

      - name: Install dependency
        run: |
          sudo apt-get update
          sudo apt-get install cmake \
                       libpcap-dev libcap-dev

      - name: Configure and Build
        shell: bash
        run: |
          mkdir ${{ matrix.arch }}
          cd ${{ matrix.arch }}
          echo "set(CMAKE_SYSTEM_NAME Linux)" >>  toolChain.cmake
          cmake .. -DCMAKE_TOOLCHAIN_FILE=./toolChain.cmake \
                   -DN2N_OPTION_USE_PORTMAPPING=ON \
                   -DN2N_OPTION_USE_PTHREAD=ON \
                   -DN2N_OPTION_USE_CAPLIB=ON  \
                   -DN2N_OPTION_USE_PCAPLIB=ON -B .
          make

      - name: Create binary dir
        shell: bash
        run: |
          cd ${{ matrix.arch }}
          make install DESTDIR=../binaries/linux_${{ matrix.arch }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: binaries


  # Given the clearly documented use of annotated tags to signal releases,
  # it seems strange that there is no simple way to trigger actions if the
  # tag is annotated.  So we need to jump through some extra hoops.
  #
  # Looking at https://github.com/actions/checkout/issues/290 seems to show
  # that github just doesnt care about how git expects annotated tags to be
  # used.
  #
  # This workflow has added a `git fetch --force --tags` to every job that
  # needs to have working tags

  upload_release:
    name: Upload Release Assets
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - binaries_windows_x64
      - binaries_windows_x86
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Get Tag Type
        id: get_tagtype
        run: |
          TYPE=$(git cat-file -t $GITHUB_REF)
          echo "::set-output name=TAGTYPE::$TYPE"
          echo ==========
          echo REF=$GITHUB_REF
          echo TAGTYPE=$TYPE

      - name: Fetch all Artifacts
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Upload Assets to Release
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            artifacts/*
