---
name: Testing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:

  binaries_windows_x64:
    name: Binaries for Windows x64
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x64]

        include:
          # Prettier run names.
          - {os: windows-2019, name: VS 2019}

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Configure and Build
        run: |
          New-Item -ItemType "directory" -Path ${{ matrix.arch }} -Force
          cd ${{ matrix.arch }}
          sed -i '/if(DEFINED WIN32)a\set(CMAKE_CXX_FLAGS_RELEASE "/MT")' ../CMakeLists.txt
          sed -i '/if(DEFINED WIN32)a\set(CMAKE_C_FLAGS_RELEASE "/MT")' ../CMakeLists.txt
          cmake.exe -G "Visual Studio 16 2019" -A ${{ matrix.arch }} -S .. -B .
          MSBuild.exe edge.vcxproj /t:Build /p:Configuration=Release
          MSBuild.exe supernode.vcxproj /t:Build /p:Configuration=Release
          MSBuild.exe n2n-benchmark.vcxproj /t:Build /p:Configuration=Release

      - name: Create binary dir
        run: |
          mkdir -p windows_${{ matrix.arch }}
          cp -r ${{ matrix.arch }}/Release windows_${{ matrix.arch }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows_${{ matrix.arch }}
          path: windows_${{ matrix.arch }}


  binaries_windows_x86:
    name: Binaries for Windows x86
    runs-on: windows-2019

    strategy:
      matrix:
        arch: [x86]

        include:
          # Prettier run names.
          - {os: windows-2019, name: VS 2019}

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Configure and Build
        run: |
          New-Item -ItemType "directory" -Path ${{ matrix.arch }} -Force
          cd ${{ matrix.arch }}
          sed -i '/if(DEFINED WIN32)a\set(CMAKE_CXX_FLAGS_RELEASE "/MT")' ../CMakeLists.txt
          sed -i '/if(DEFINED WIN32)a\set(CMAKE_C_FLAGS_RELEASE "/MT")' ../CMakeLists.txt
          cmake.exe -G "Visual Studio 16 2019" -A Win32 -S .. -B .
          MSBuild.exe edge.vcxproj /t:Build /p:Configuration=Release
          MSBuild.exe supernode.vcxproj /t:Build /p:Configuration=Release
          MSBuild.exe n2n-benchmark.vcxproj /t:Build /p:Configuration=Release

      - name: Create binary dir
        run: |
          mkdir -p windows_${{ matrix.arch }}
          cp -r ${{ matrix.arch }}/Release windows_${{ matrix.arch }}

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows_${{ matrix.arch }}
          path: windows_${{ matrix.arch }}


  # Given the clearly documented use of annotated tags to signal releases,
  # it seems strange that there is no simple way to trigger actions if the
  # tag is annotated.  So we need to jump through some extra hoops.
  #
  # Looking at https://github.com/actions/checkout/issues/290 seems to show
  # that github just doesnt care about how git expects annotated tags to be
  # used.
  #
  # This workflow has added a `git fetch --force --tags` to every job that
  # needs to have working tags

  upload_release:
    name: Upload Release Assets
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - binaries_windows_x64
      - binaries_windows_x86
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Get Tag Type
        id: get_tagtype
        run: |
          TYPE=$(git cat-file -t $GITHUB_REF)
          echo "::set-output name=TAGTYPE::$TYPE"
          echo ==========
          echo REF=$GITHUB_REF
          echo TAGTYPE=$TYPE

      - name: Fetch all Artifacts
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Upload Assets to Release
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            artifacts/*
