---
name: Testing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  smoketest:
    name: Smoke test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run minimal test set
        run: |
          ./autogen.sh
          ./configure
          make test

  test_windows:
    needs: smoketest
    name: Test Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-2019
          - windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: generate a makefile and use it to install more packages
        run: |
          # This is a pretty big hammer, but gets the windows compile moving
          export AR='ar'
        shell: bash


  binaries_windows_32:
    name: Binaries for Windows (i686-pc-mingw64)
    needs:
      - test_windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags
      - name: Configure and Build
        shell: bash
        run: |
          export FIXME='happynet3.0.0'
          export AR='ar --target=pe-i386'
          export CFLAGS='-m32 '
          export LDFLAGS='-m32 '
          source scripts/hack_fakeautoconf.sh
          make
      - name: Create binary dir
        shell: bash
        run: |
          make install DESTDIR=binaries/i686-pc-mingw64

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: binaries


  # Given the clearly documented use of annotated tags to signal releases,
  # it seems strange that there is no simple way to trigger actions if the
  # tag is annotated.  So we need to jump through some extra hoops.
  #
  # Looking at https://github.com/actions/checkout/issues/290 seems to show
  # that github just doesnt care about how git expects annotated tags to be
  # used.
  #
  # This workflow has added a `git fetch --force --tags` to every job that
  # needs to have working tags

  upload_release:
    name: Upload Release Assets
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - binaries_windows_32
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Get Tag Type
        id: get_tagtype
        run: |
          TYPE=$(git cat-file -t $GITHUB_REF)
          echo "::set-output name=TAGTYPE::$TYPE"
          echo ==========
          echo REF=$GITHUB_REF
          echo TAGTYPE=$TYPE

      - name: Fetch all Artifacts
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Upload Assets to Release
        if: steps.get_tagtype.outputs.TAGTYPE == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            artifacts/packages-dpkg/*.deb
            artifacts/packages-rpm/*.rpm
